"""Campo grupo añadido en partidos

Revision ID: 1a35b2b79a0a
Revises: 1b25dfccad98
Create Date: 2024-11-05 15:03:28.941435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a35b2b79a0a'
down_revision = '1b25dfccad98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
