"""Añadiendo relacion bidireccional a inscripcion-equipo

Revision ID: 1b25dfccad98
Revises: d419a26fe305
Create Date: 2024-11-02 17:56:36.811872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b25dfccad98'
down_revision = 'd419a26fe305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['equipo_id'])
        batch_op.create_foreign_key(None, 'equipos', ['equipo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###
