"""partido-cancha --> nullable

Revision ID: 44353205c635
Revises: edb539784f1f
Create Date: 2024-11-19 16:15:09.151528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44353205c635'
down_revision = 'edb539784f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.alter_column('cancha',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.alter_column('cancha',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
