"""Actualizamos los datos de Partidos

Revision ID: 819f7e24f82b
Revises: 1a35b2b79a0a
Create Date: 2024-11-05 16:02:48.551879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '819f7e24f82b'
down_revision = '1a35b2b79a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.alter_column('puntaje1',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('puntaje2',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.alter_column('puntaje2',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('puntaje1',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
