"""Cupos y settings

Revision ID: 8961bd1b5f2a
Revises: 44353205c635
Create Date: 2025-01-28 18:14:34.956073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8961bd1b5f2a'
down_revision = '44353205c635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.drop_column('cupos disponibles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupos disponibles', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
