"""Actualización de modelos Inscripcion y Settings

Revision ID: d419a26fe305
Revises: 
Create Date: 2024-11-02 15:00:31.049820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd419a26fe305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('colegio', sa.String(length=100), nullable=False),
    sa.Column('deporte', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=False),
    sa.Column('victorias', sa.Integer(), nullable=False),
    sa.Column('empates', sa.Integer(), nullable=False),
    sa.Column('derrotas', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index('idx_deporte_categoria', ['deporte', 'categoria'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('gmail', sa.String(length=30), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deporte', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.Column('cancha', sa.Integer(), nullable=False),
    sa.Column('equipo1_id', sa.Integer(), nullable=False),
    sa.Column('equipo2_id', sa.Integer(), nullable=False),
    sa.Column('puntaje1', sa.Integer(), nullable=False),
    sa.Column('puntaje2', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipo1_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Partidos')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Gmail', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Contraseña', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ROL', mysql.TINYTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Partidos',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Equipo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Deporte', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Grupo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Empates', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Victorias', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Derrotas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GF', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GC', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Puntos', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('partidos')
    op.drop_table('usuarios')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index('idx_deporte_categoria')

    op.drop_table('equipos')
    # ### end Alembic commands ###
